repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  -   id: check-yaml
  -   id: end-of-file-fixer
  -   id: trailing-whitespace
  -   id: check-added-large-files
  -   id: fix-byte-order-marker
  -   id: check-docstring-first
  -   id: mixed-line-ending
  -   id: check-case-conflict
  -   id: check-ast
  -   id: requirements-txt-fixer

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.11
  hooks:
    # Run the linter.
    - id: ruff
      args: ["--extend-select=I", "--fix"]
    # Run the formatter.
    - id: ruff-format
