repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  -   id: check-yaml
  -   id: end-of-file-fixer
  -   id: trailing-whitespace
  -   id: check-added-large-files
  -   id: fix-byte-order-marker
  -   id: check-docstring-first
  -   id: mixed-line-ending
  -   id: check-case-conflict
  -   id: check-ast
  -   id: requirements-txt-fixer

# Format markdown docs.
-   repo: https://github.com/executablebooks/mdformat
    # Do this before other tools "fixing" the line endings
    rev: 0.7.18
    hooks:
    -   id: mdformat
        args: [--number, --end-of-line=keep]
        additional_dependencies:
            - mdformat-toc
            - mdformat-config
            - mdformat-gfm

# Format and lint python code.
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.7.0
  hooks:
    # Run the linter.
    - id: ruff
      args: ["--extend-select=I", "--fix"]
    # Run the formatter.
    - id: ruff-format

# Catch typos!
-   repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
    -   id: codespell
